export const couple1Params = {
  "backgroundArray": [
    "cat-1-background",
    "cat-2-background",
    "cat-3-background",
    "cat-4-background",
    "cat-5-background",
    "cat-6-background",
    "cat-7-background",
    "cat-8-background",
    "cat-9-background",
    "cat-10-background",
    "cat-11-background",
    "cat-12-background",
    "cat-1-background",
    "cat-2-background",
    "cat-3-background",
    "cat-4-background",
    "cat-5-background",
    "cat-6-background",
    "cat-7-background",
    "cat-8-background",
    "cat-9-background",
    "cat-10-background",
    "cat-11-background",
    "cat-12-background",
    "cat-1-background",
    "cat-2-background",
    "cat-3-background",
    "cat-4-background",
    "cat-5-background",
    "cat-6-background",
    "black-background"
  ],
  "leftText": [
    "Estar contigo me hace feliz.",
    "No puedo imaginar mi vida sin ti.",
    "Te amo.",
    "Eres mi mejor amiga y mi gran amor.",
    "Cada día a tu lado es un regalo.",
    "Eres mi sueño hecho realidad.",
    "Contigo, todo es mejor.",
    "Me encanta tu sonrisa.",
    "Me haces querer ser una mejor persona.",
    "Podria perderme en tus ojitos.",
    "Gracias por existir y por estar conmigo.",
    "Cada día te quiero más.",
    "Me das paz.",
    "Te adoro con todo mi corazón.",
    "Haces que cualquier día se vuelva bueno.",
    "No hay nadie como tú.",
    "Eres mi todo.",
    "Estoy orgulloso de tí.",
    "Cada momento contigo es especial.",
    "Un futuro juntos le da sentido a mi vida.",
    "Te elijo a ti, una y otra vez.",
    "Gracias por ser tú.",
    "Puedes con todo lo que te propongas.",
    "Contigo, todo es posible.",
    "Eres mi mayor tesoro.",
    "Si estoy contigo no necesito nada más.",
    "Te quiero más de lo que nunca imaginé.",
    "Eres mi complemento perfecto.",
    "Mi amor por ti es infinito.",
    "Eres mi razón para sonreír cada día."
  ]
}